In [21]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
revendedores = pd.read_csv("data/revendedores.csv", sep=';', encoding='utf8')
revendedores.head()

,CODIGOISIMP,AUTORIZACAO,DATAPUBLICACAO,RAZAOSOCIAL,CNPJ,ENDERECO,COMPLEMENTO,BAIRRO,CEP,UF,MUNICIPIO,BANDEIRA,DATAVINCULACAO
0,1022007,PR/SP0019777,23/01/2002,AUTO POSTO SAKAMOTO LTDA,49051667000102,"RODOVIA PRESIDENTE DUTRA, S/N","KM 210,5-SENT SP/RJ",BONSUCESSO,7178580,SP,GUARULHOS,VIBRA,23/01/2002
1,1227493,PR/PI0177467,28/09/2016,POSTO RAMALEY LTDA,19052407000190,"R SAO NICOLAU, 940",NaN,CENTRO,64315000,PI,SANTA CRUZ DOS MILAGRES,BANDEIRA BRANCA,28/09/2016
2,1000022,PR/SP0021686,28/02/2002,COMPETRO COMERCIO E DISTRIBUICAO DE DERIVADOS ...,3188000474,"AVENIDA SANTOS DUMONT, 701",NaN,AEROPORTO,18065290,SP,SOROCABA,BANDEIRA BRANCA,27/07/2018
3,1175475,AV/SP0088382,12/07/2011,M & J COMÉRCIO DE COMBUSTÍVEIS E LUBRIFICANTES...,5678449000127,"AVENIDA EMILIO ANTONON, S/N",NaN,CHACARA AEROPORTO,13212010,SP,JUNDIAI,RAIZEN,12/07/2011
4,1226945,PR/RS0177246,14/09/2016,METROPOLITANO COMERCIO DE COMBUSTIVEIS LTDA,88587589000621,"RUA BOQUEIRAO, 1401",NaN,IGARA,92410350,RS,CANOAS,BANDEIRA BRANCA,14/09/2016

In [3]:
fiscal = pd.read_csv("data/fiscalizacao.csv", sep=';', encoding='latin1')
fiscal.head()

/tmp/ipykernel_59397/3595633622.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  fiscal = pd.read_csv("data/fiscalizacao.csv", sep=';', encoding='latin1')

,UF,Município,Bairro,Endereço,CNPJ/CPF,Agente Econômico,Segmento Fiscalizado,Data DF,Número do Documento,Procedimento de Fiscalização,Resultado
0,AC,ACRELANDIA,ZONA RURAL,"RODOVIA BR 364 KM 96, M. DIREITA SENTIDO RIO B...",07481893000183,AUTO POSTO CAMARINI EIRELI,Revenda de Combustíveis,08/07/2020,575385,Boletim de Fiscalização,Ação de fiscalização em campo
1,AC,ACRELANDIA,ZONA RURAL,"RODOVIA BR 364 KM 96, M. DIREITA SENTIDO RIO B...",07481893000183,AUTO POSTO CAMARINI EIRELI,Revenda de Combustíveis,08/07/2020,575385,Medida Reparadora de Conduta,MRC - PR Comb - Afixação de aviso sobre o Óleo...
2,AC,ACRELANDIA,ZONA RURAL,"RODOVIA BR 364 KM 96, M. DIREITA SENTIDO RIO B...",07481893000183,AUTO POSTO CAMARINI EIRELI,Revenda de Combustíveis,08/07/2020,575385,Boletim de Fiscalização,Ação de Fiscalização - Outras Situações
3,AC,ACRELANDIA,ZONA RURAL,"RODOVIA BR 364 KM 96, M. DIREITA SENTIDO RIO B...",07481893000183,AUTO POSTO CAMARINI EIRELI,Revenda de Combustíveis,08/07/2020,575385,Boletim de Fiscalização,ATIV ECON - Revenda de Combustíveis
4,AC,ACRELANDIA,ZONA RURAL,"RODOVIA BR 364 KM 96, M. DIREITA SENTIDO RIO B...",07481893000183,AUTO POSTO CAMARINI EIRELI,Revenda de Combustíveis,08/07/2020,575385,Medida Reparadora de Conduta,MRC - PR Comb - Preços de combustíveis com 03 ...

In [4]:
branca = revendedores[["CNPJ", "BANDEIRA"]].loc[revendedores["BANDEIRA"] == "BANDEIRA BRANCA"]

In [5]:
n_branca = revendedores[["CNPJ", "BANDEIRA"]].loc[revendedores["BANDEIRA"] != "BANDEIRA BRANCA"]

In [6]:
branca.count()

CNPJ        21032
BANDEIRA    21032
dtype: int64

In [7]:
n_branca.count()

CNPJ        23359
BANDEIRA    23359
dtype: int64

In [8]:
fiscal.count()

UF                              427802
Município                       427802
Bairro                          427561
Endereço                        427802
CNPJ/CPF                        427802
Agente Econômico                427190
Segmento Fiscalizado            427771
Data DF                         427802
Número do Documento             427802
Procedimento de Fiscalização    427802
Resultado                       427802
dtype: int64

In [9]:
first_rows = fiscal[["CNPJ/CPF", "Número do Documento", "Data DF"]].groupby('Número do Documento').apply(lambda x: x.iloc[0]).reset_index(drop=True)
first_rows.head()

/tmp/ipykernel_59397/1758821198.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  first_rows = fiscal[["CNPJ/CPF", "Número do Documento", "Data DF"]].groupby('Número do Documento').apply(lambda x: x.iloc[0]).reset_index(drop=True)

         CNPJ/CPF  Número do Documento     Data DF
0  26307505000197                 1851  28/01/2019
1   3341764000139                 1852  29/01/2019
2   4102376000168                 1853  29/01/2019
3  19279262000165                 1854  30/01/2019
4  10370109000174                 1855  30/01/2019

In [10]:
first_rows.count()

CNPJ/CPF               110658
Número do Documento    110658
Data DF                110658
dtype: int64

In [11]:
revend_info = revendedores[["CNPJ", "BANDEIRA"]]
revend_info.head()

             CNPJ         BANDEIRA
0  49051667000102            VIBRA
1  19052407000190  BANDEIRA BRANCA
2      3188000474  BANDEIRA BRANCA
3   5678449000127           RAIZEN
4  88587589000621  BANDEIRA BRANCA

In [12]:
merged = pd.merge(first_rows, revend_info, left_on="CNPJ/CPF", right_on="CNPJ", how="left")
merged = merged[["CNPJ/CPF", "Data DF", "BANDEIRA"]].dropna()

In [13]:
merged.head(100)

           CNPJ/CPF     Data DF         BANDEIRA
1     3341764000139  29/01/2019            VIBRA
2     4102376000168  29/01/2019         IPIRANGA
3    19279262000165  30/01/2019           RODOIL
5    80997000000147  31/01/2019  BANDEIRA BRANCA
6     3799489000100  31/01/2019         IPIRANGA
..              ...         ...              ...
161  15971203000100  27/03/2018            VIBRA
162   1941947000160  27/03/2018            VIBRA
164  26406017000137  11/04/2018            VIBRA
165  15922776000136  12/04/2018           RAIZEN
166   3742012000180  11/04/2018  BANDEIRA BRANCA

[100 rows x 3 columns]

In [14]:
merged.loc[merged["BANDEIRA"] == "BANDEIRA BRANCA"]

              CNPJ/CPF     Data DF         BANDEIRA
5       80997000000147  31/01/2019  BANDEIRA BRANCA
10      68575349000195  30/01/2019  BANDEIRA BRANCA
18      33779216000156  16/04/2019  BANDEIRA BRANCA
30      19878460000145  04/02/2019  BANDEIRA BRANCA
32        590065000134  05/02/2019  BANDEIRA BRANCA
...                ...         ...              ...
110634   8208910000176  10/11/2022  BANDEIRA BRANCA
110645  33312532000113  10/02/2023  BANDEIRA BRANCA
110647  26932978000185  10/02/2023  BANDEIRA BRANCA
110652   7805436000105  13/02/2023  BANDEIRA BRANCA
110653  34195936000137  13/02/2023  BANDEIRA BRANCA

[24950 rows x 3 columns]

In [15]:
merged.loc[merged["BANDEIRA"] != "BANDEIRA BRANCA"]

              CNPJ/CPF     Data DF  BANDEIRA
1        3341764000139  29/01/2019     VIBRA
2        4102376000168  29/01/2019  IPIRANGA
3       19279262000165  30/01/2019    RODOIL
6        3799489000100  31/01/2019  IPIRANGA
9        7877289000170  30/01/2019    RAIZEN
...                ...         ...       ...
110648   6703805001079  12/02/2023     VIBRA
110649   6703805001079  12/02/2023     VIBRA
110655  15614669000140  13/02/2023        SP
110656  12837527000154  14/02/2023        SP
110657  12837527000154  14/02/2023        SP

[33067 rows x 3 columns]

In [25]:
merged["BANDEIRA"].value_counts(normalize=True)

BANDEIRA
BANDEIRA BRANCA         0.430046
VIBRA                   0.179913
IPIRANGA                0.153369
RAIZEN                  0.139494
ALESAT                  0.025630
RODOIL                  0.009377
SABBÁ                   0.008842
TOTALENERGIES           0.005809
CHARRUA                 0.005050
TAURUS                  0.003809
RAIZEN MIME             0.003671
PETROX DISTRIBUIDORA    0.003275
ATLÂNTICA               0.002344
STANG                   0.002172
POTENCIAL               0.002034
IDAZA                   0.002034
DISLUB                  0.001775
EQUADOR                 0.001741
ATEM' S                 0.001724
SP                      0.001551
CIAPETRO                0.001482
SETTA DISTRIBUIDORA     0.001482
MAXSUL                  0.001241
AIR BP                  0.001034
RIO BRANCO              0.000982
DIBRAPE                 0.000948
WATT                    0.000793
SANTA LUCIA             0.000741
FAN                     0.000724
FEDERAL ENERGIA         0.000672
LARCO                   0.000586
AMERICANOIL             0.000569
WALENDOWSKY             0.000569
TEMAPE                  0.000517
SMALL                   0.000483
TDC DISTRIBUIDORA       0.000465
SIMARELLI               0.000465
PETROBAHIA              0.000448
RDP ENERGIA             0.000431
MASUT DISTRIBUIDORA     0.000310
TORRAO                  0.000259
PELIKANO                0.000224
D`MAIS                  0.000224
RUFF C.J.               0.000190
ALCOOLBRAS              0.000086
ACOL                    0.000069
IMPERIAL                0.000052
PETROBRASIL             0.000052
UNI                     0.000052
ESTRADA                 0.000052
ON PETRO                0.000052
SAARA                   0.000034
AIR BP PETROBAHIA       0.000034
ROYAL FIC               0.000017
Name: proportion, dtype: float64